### ISSUE TITLE
Re-license to BSD

### ISSUE THREAD

**Issue by vincenthz** [djs55/ocaml-sha#22]
The license is currently GPL2 without any exceptions, and this is causing problems. I'll like all the ocaml-sha source code to be relicensed under BSD (all the .c .h are effectively already under this license in the haskell packages where you can find them)

Also there's one line contributed by @samoht, please add your agreement/disagreement here

adding @avsm

**Comment by samoht** [comment]
I agree.

**Comment by djs55** [comment]
There's also code from the following people:

- ada51a77b71c358603b14c5c0b60a8685216b81e: missing big array functions from  Goswin von Brederlow (@mrvn ?)
- 02e2685b07412d3bd445474d92a6d7efce039170: a comment fix from Eric Cooper (will email separately)
- d70bbff1da0e19a577281432f0b591a18152fb8a ac38f289d6321e4ad5fdd4dc3ba9fc1aaf992a3b: build fixes from Florent Monnier (@fccm ?)
- 162ba4d0818349422c099ae4a17bd3c3371fd68b 001dfc58067f9b454752a175eb86e4fb0ca4a890: build fixes from Forrest L Norvell (will email separately)
- 9b171d0dfcb5497c19e09f002945afc2721e6e08: endianness improvements by Vincent Bernadoff (@vbmithr)

Could you let me know whether you agree or disagree with relicensing your contributions to `ocaml-sha` under the [ISC variant of the BSD license](https://opensource.org/licenses/ISC)?

Thanks!

**Comment by vbmithr** [comment]
Le 07/10/2017 à 10:50, David Scott a écrit :
> 9b171d0
> <https://github.com/djs55/ocaml-sha/commit/9b171d0dfcb5497c19e09f002945afc2721e6e08>:
> endianness improvements by Vincent Bernadoff (@vbmithr
> <https://github.com/vbmithr>)

Agreed.

-- 
Vincent

**Comment by othiym23** [comment]
Agreed.

**Comment by nojb** [comment]
Any news on this?

**Comment by djs55** [comment]
Eric tells me he agrees via email, so that just leaves

- from Goswin (@mrvn ?) (I missed a few on my first walk through)
  - ada51a77b71c358603b14c5c0b60a8685216b81e: missing big array functions
  - 4f91e7838eebaece22a7cc0c7b2e698a00ecccdd: safe string functions
  - 1683dd5cb1811e015c9e38780a06496ede40e90e: context copy function
  - fc3eb63a02b0ca180b1a8e66ab0384be3db4a64a: incremental checksumming
  - ec9d5ab1cee84af30879a641f17335b74e1da918: release the runtime lock
- from Florent (@fccm ?)
  - d70bbff1da0e19a577281432f0b591a18152fb8a ac38f289d6321e4ad5fdd4dc3ba9fc1aaf992a3b: build fixes (@fccm ?)

I'll send each of them an email in case they don't check their github notifications (or in case I guessed the wrong github id)

**Comment by nojb** [comment]
Sorry to be a nag, but any news on this? (I would like to use `ocaml-sha` for a project, but the license is a problem currently).

**Comment by mrvn** [comment]
I agree, sorry for the delay.

**Comment by djs55** [comment]
Thanks everyone (and sorry for the delay on my part too). Since the remaining patches are build fixes I don't think I need to worry about them.

**Comment by nojb** [comment]
Are you planning a new release with the new license?

**Comment by djs55** [comment]
@nojb I'll change the license headers and make a new release today.

**Comment by nojb** [comment]
Great, thanks!

**Comment by djs55** [comment]
@nojb release in progress: https://github.com/ocaml/opam-repository/pull/11146
